# Generated by Django 4.1.6 on 2023-02-11 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_fungi_date_collected_alter_fungi_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fungi',
            name='user',
        ),
    ]
