# Generated by Django 4.1.6 on 2023-02-11 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_fungi_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FungiNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('fungi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.fungi')),
            ],
        ),
    ]
