# Generated by Django 4.1.6 on 2023-02-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_habitat_alter_funginote_note_fungi_habitats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fungi',
            name='habitats',
            field=models.ManyToManyField(related_name='fungi', to='main_app.habitat'),
        ),
    ]
