# Generated by Django 4.2.6 on 2023-10-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_fungi_habitats'),
    ]

    operations = [
        migrations.AddField(
            model_name='fungi',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='fungi_photos/'),
        ),
    ]
