# Generated by Django 4.2.6 on 2023-10-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_comment_delete_funginote'),
    ]

    operations = [
        migrations.AddField(
            model_name='fungi',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
