# Generated by Django 4.2.6 on 2024-01-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_fungi_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='fungi',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
