# Generated by Django 4.2.6 on 2024-01-14 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0013_fungi_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fungi',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_fungi', to=settings.AUTH_USER_MODEL),
        ),
    ]
